# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-22 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('all_hotels', '0002_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='check_out',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='no_of_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
