# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-22 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_hotels', '0004_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='location_city',
        ),
    ]
