# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-22 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_hotels', '0005_auto_20181122_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_city', models.CharField(max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_hotels.Hotel')),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
