# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-25 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_hotels', '0006_auto_20181122_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_bed', models.CharField(max_length=100, null=True)),
                ('double_bed', models.CharField(max_length=100, null=True)),
                ('delux', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='location_city',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='Location_city',
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.ManyToManyField(to='all_hotels.Price'),
        ),
    ]
