# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-25 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_hotels', '0007_auto_20181125_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
