# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-25 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_hotels', '0008_price_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='name',
        ),
        migrations.AddField(
            model_name='price',
            name='name_p',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
