# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-25 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_hotels', '0009_auto_20181125_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='name_p',
            new_name='namep',
        ),
    ]
