# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-25 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_hotels', '0011_auto_20181125_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='double_bed',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='delux',
        ),
        migrations.RemoveField(
            model_name='price',
            name='namep',
        ),
        migrations.RemoveField(
            model_name='price',
            name='single_bed',
        ),
    ]
