# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-25 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_hotels', '0012_auto_20181125_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='available_rooms',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
